In [1]:
import numpy as np

# Creating Arrays

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [6]:
m = np.array([ [7,8,9],[10,11,12] ])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
m.shape

(2, 3)

In [9]:
# start,stop,step
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [15]:
# start,stop,number
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [16]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [26]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
2*p

array([[2, 2, 2],
       [2, 2, 2]])

In [31]:
p*2

array([[2, 2, 2],
       [2, 2, 2]])

In [33]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [37]:
x+y

array([5, 7, 9])

In [38]:
x*y

array([ 4, 10, 18])

In [39]:
x**2

array([1, 4, 9], dtype=int32)

In [40]:
x.dot(y)

32

In [41]:
z = np.array((y, y**2))
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [42]:
z.shape

(2, 3)

In [43]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [44]:
z.T.shape

(3, 2)

In [45]:
z.dtype

dtype('int32')

In [47]:
# change type
z = z.astype('f')
z.dtype

dtype('float32')

In [48]:
a = np.array([-4,-2,1,3,5])

In [49]:
a.sum()

3

In [50]:
a.max()

5

In [51]:
a.min()

-4

In [52]:
a.mean()

0.6

In [53]:
a.std()

3.2619012860600183

In [54]:
a.argmax()

4

In [55]:
a.argmin()

0

# Indexing / Slicing

In [56]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [58]:
s[0],s[4],s[:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [59]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [60]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [65]:
# start 5th from the end, counting backwards by 2
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [67]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [68]:
r[2,2]

14

In [69]:
r[3, 3:6]

array([21, 22, 23])

In [70]:
r[:2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [75]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [76]:
r[r>30]

array([31, 32, 33, 34, 35])

In [77]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copy and Slice

In [81]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [82]:
# r2 = 0
# r2
# will print(int 0)

r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
# r is also changed
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [84]:
# Use copy() to avoid this
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [86]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Arrays

In [91]:
# start,stop,size
test = np.random.randint(0,10,(4,3))
test

array([[3, 9, 6],
       [5, 6, 0],
       [9, 0, 0],
       [8, 3, 1]])

In [104]:
for row in test:
    print(row)

[3 9 6]
[5 6 0]
[9 0 0]
[8 3 1]


In [96]:
# number of row
len(test)

4

In [98]:
test[2]

array([9, 0, 0])

In [97]:
for i in range (len(test)):
    print(test[i])

[3 9 6]
[5 6 0]
[9 0 0]
[8 3 1]


In [99]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [3 9 6]
row 1 is [5 6 0]
row 2 is [9 0 0]
row 3 is [8 3 1]


In [100]:
test2 = test**2
test2

array([[ 9, 81, 36],
       [25, 36,  0],
       [81,  0,  0],
       [64,  9,  1]], dtype=int32)

In [101]:
test

array([[3, 9, 6],
       [5, 6, 0],
       [9, 0, 0],
       [8, 3, 1]])

In [102]:
# i:test ; j:test2
for i,j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[3 9 6] + [ 9 81 36] = [12 90 42]
[5 6 0] + [25 36  0] = [30 42  0]
[9 0 0] + [81  0  0] = [90  0  0]
[8 3 1] + [64  9  1] = [72 12  2]
